version: "3.9"
services:
  key-service:
    build: ./key_service
    container_name: key-service
    ports:
      - "8000:8000"
    volumes:
      - ./keys:/app/keys
    environment:
      - PUBLIC_KEY_PATH=/app/keys/public.pem

  session-service:
    build: ./session_service
    container_name: session-service
    ports:
      - "8001:8000"
    volumes:
      - ./keys:/app/keys
    depends_on:
      - key-service
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  metrics-service:
    build: ./metrics_service
    ports:
      - "8004:8000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"
  
  client:
    build: ./client
    container_name: chat-client
    ports:
      - "5173:80"
    depends_on:
      - key-service
      - session-service
