version: "3.9"
services:
  key-service:
    build: ./key_service
    ports:
      - "8001:8000"
    volumes:
      - ./keys:/app/keys
    environment:
      - KEY_PATH=/app/keys/server_rsa.pem

  session-service:
    build: ./session_service
    ports:
      - "8002:8000"
    depends_on:
      - key-service
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  chat-service:
    build: ./chat_service
    ports:
      - "8003:8000"
    depends_on:
      - session-service
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  metrics-service:
    build: ./metrics_service
    ports:
      - "8004:8000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  server:
    build: ./server
    container_name: chat_server
    ports:
      - "3001:3001"
  
  client:
    build: ./client
    container_name: chat_client
    ports:
      - "5173:80"
    depends_on:
      - server
