global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "key-service"
    static_configs:
      - targets: ["key-service:8000"]

  - job_name: "session-service"
    static_configs:
      - targets: ["session-service:8000"]